# Generated by Django 4.1.7 on 2023-03-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('partner_id', models.IntegerField()),
                ('products', models.JSONField()),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'PAID'), ('unpaid', 'UNPAID'), ('no_payment_required', 'NO PAYMENT REQUIRED')], default='unpaid', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
