# Generated by Django 4.1.7 on 2023-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_id',
            field=models.CharField(max_length=255),
        ),
    ]
